[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 毕业论文管理系统

## 登录注册模块
> collapsed=`true`,leftSide=`true`


### 登录
> collapsed=`true`


#### 用户名密码核对
> collapsed=`true`


##### 正确
> collapsed=`true`


###### 查找用户名对应的用户类型
> collapsed=`true`


####### 根据用户类型进入不同首页

##### 错误
> collapsed=`true`


###### 弹出错误提示
> collapsed=`true`


####### 重新输入

### 注册
> collapsed=`true`


#### 选择用户类型
> collapsed=`true`


##### 学生
> collapsed=`true`


###### 用户信息注册

##### 教师
> collapsed=`true`


###### 提供注册码\(管理员预设值\)
> collapsed=`true`


####### 用户信息注册

##### 教务
> collapsed=`true`


###### 提供注册码\(管理员预设值\)
> collapsed=`true`


####### 用户信息注册

## 学生模块
> collapsed=`true`


### 学生个人信息
> collapsed=`true`


#### 查看

#### 修改

### 课题申报
> collapsed=`true`


#### 申报课题
> collapsed=`true`


##### 填写

#### 开题报告
> collapsed=`true`


##### 填写

#### 任务书
> collapsed=`true`


##### 填写

#### 中期检查
> collapsed=`true`


##### 填写

### 论文管理
> collapsed=`true`


#### 初稿
> collapsed=`true`


##### 提交

##### 修改

##### 格式检测

##### 查重

#### 定稿
> collapsed=`true`


##### 提交

##### 查重

#### 最终稿
> collapsed=`true`


##### 提交

### 答辩管理
> collapsed=`true`


#### 答辩小组

#### 答辩信息

### 教师评价

### 材料导出

### 特殊情况处理
> collapsed=`true`


#### 开题报告修改

#### 论文定稿修改

#### 评阅教师评阅退回

#### 论文最终稿修改

### 公告信息
> collapsed=`true`


#### 查看

#### 确认

## 教师模块
> collapsed=`true`


### 教师个人信息
> collapsed=`true`


#### 查看

#### 修改

### 公告信息
> collapsed=`true`


#### 查看

#### 确认

### 组员管理
> collapsed=`true`


#### 查看

### 流程管理
> collapsed=`true`


#### 课题申报审核

#### 开题报告审核

#### 中期检查审核

#### 论文初稿审核

#### 论文定稿审核

#### 论文最终稿审核

#### 答辩结果填写

## 管理员模块
> collapsed=`true`,leftSide=`true`


### 用户信息管理
> collapsed=`true`


#### 增加

#### 删除

#### 修改

#### 查询

## 教务模块
> collapsed=`true`,leftSide=`true`


### 学生信息管理
> collapsed=`true`


#### 增加

#### 删除

#### 修改

#### 查询

#### 分组

### 教师信息管理
> collapsed=`true`


#### 组员查询

#### 个人信息查询

### 流程信息管理
> collapsed=`true`


#### 课题申报

#### 开题报告

#### 中期检查

#### 论文

#### 答辩
